// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $SignupForm from "./islands/SignupForm.tsx";
import * as $form_Password from "./islands/form/Password.tsx";
import * as $form_Text from "./islands/form/Text.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/signup.tsx": $signup,
  },
  islands: {
    "./islands/SignupForm.tsx": $SignupForm,
    "./islands/form/Password.tsx": $form_Password,
    "./islands/form/Text.tsx": $form_Text,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
